version: '3.7'
services:
  mongodb:
    image: mongo:latest
    command: mongod --port 27018
    container_name: light-weight-mongodb-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27018:27018
    volumes:
      - light-weight-mongodb-data-container-volume:/data/_db

volumes:
  light-weight-mongodb-data-container-volume:
